# Generated by Django 3.1.2 on 2020-11-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Host', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobCitySetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPositionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobTransparencyLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TechTrans', models.TextField(unique=True)),
                ('TechTransCheck', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobTypeFind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jobtype', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaxResultsPerCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaxNumber', models.IntegerField()),
            ],
        ),
    ]
