# Generated by Django 3.1.2 on 2021-01-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Host', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobCitySetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobPositionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobTransparencyLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TechTrans', models.CharField(max_length=500)),
                ('TechTransCheck', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='JobTypeFind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jobtype', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MaxAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MaxResultsPerCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaxNumber', models.IntegerField()),
            ],
        ),
    ]
