# Generated by Django 3.1.2 on 2020-11-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField()),
            ],
        ),
    ]
